//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
// Generated on: 2016.07.29 at 05:51:25 PM SAST 
=======
<<<<<<< HEAD
// Generated on: 2016.07.28 at 11:38:03 PM CAT 
=======
// Generated on: 2016.07.29 at 03:01:08 AM CAT 
>>>>>>> ab2bb0bad3bbede04c50fda59926e3b121ebf0e2
>>>>>>> 1f0d0cddfdb9f36f8100e5dc456100746d646cb3
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://spring.io/guides/gs-producing-web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.spring.guides.gs_producing_web_service;
