//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.17 at 04:16:04 PM CAT 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="votingNode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="partyNode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="voteType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "votingNode",
    "partyNode",
    "voteType"
})
@XmlRootElement(name = "sendVoteRequest")
public class SendVoteRequest {

    @XmlElement(required = true)
    protected String votingNode;
    @XmlElement(required = true)
    protected String partyNode;
    @XmlElement(required = true)
    protected String voteType;

    /**
     * Gets the value of the votingNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVotingNode() {
        return votingNode;
    }

    /**
     * Sets the value of the votingNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVotingNode(String value) {
        this.votingNode = value;
    }

    /**
     * Gets the value of the partyNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyNode() {
        return partyNode;
    }

    /**
     * Sets the value of the partyNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyNode(String value) {
        this.partyNode = value;
    }

    /**
     * Gets the value of the voteType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoteType() {
        return voteType;
    }

    /**
     * Sets the value of the voteType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoteType(String value) {
        this.voteType = value;
    }

}
