//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
// Generated on: 2016.07.29 at 05:51:25 PM SAST 
=======
<<<<<<< HEAD
// Generated on: 2016.07.28 at 11:38:03 PM CAT 
=======
// Generated on: 2016.07.29 at 03:01:08 AM CAT 
>>>>>>> ab2bb0bad3bbede04c50fda59926e3b121ebf0e2
>>>>>>> 1f0d0cddfdb9f36f8100e5dc456100746d646cb3
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sendVote complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sendVote"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VotingNode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PartyNode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VoteType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendVote", propOrder = {
    "votingNode",
    "partyNode",
    "voteType",
    "success"
})
public class SendVote {

    @XmlElement(name = "VotingNode", required = true)
    protected String votingNode;
    @XmlElement(name = "PartyNode", required = true)
    protected String partyNode;
    @XmlElement(name = "VoteType", required = true)
    protected String voteType;
    protected boolean success;

    /**
     * Gets the value of the votingNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVotingNode() {
        return votingNode;
    }

    /**
     * Sets the value of the votingNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVotingNode(String value) {
        this.votingNode = value;
    }

    /**
     * Gets the value of the partyNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyNode() {
        return partyNode;
    }

    /**
     * Sets the value of the partyNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyNode(String value) {
        this.partyNode = value;
    }

    /**
     * Gets the value of the voteType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoteType() {
        return voteType;
    }

    /**
     * Sets the value of the voteType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoteType(String value) {
        this.voteType = value;
    }

    /**
     * Gets the value of the success property.
     * 
     */
    public boolean isSuccess() {
        return success;
    }

    /**
     * Sets the value of the success property.
     * 
     */
    public void setSuccess(boolean value) {
        this.success = value;
    }

}
